name: Deploy to Wiki
on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Retrieve authentication token
        id: get-token
        # SHA1 hash of the release-v0.0.1 commit.
        uses: oppia/get-github-app-token@8c3b19db0cdcd0f7fded7dd71e5e0429bf72df1a
        with:
          app_id: ${{ secrets.OPPIA_WIKI_SYNCHRONIZER_APP_ID }}
          private_key: ${{ secrets.OPPIA_WIKI_SYNCHRONIZER_APP_PRIVATE_KEY }}
      - uses: actions/checkout@v2
        with:
          token: ${{ steps.get-token.outputs.token }}
          fetch-depth: 0
      - name: Add remote
        run: git remote add deployment https://github.com/${{github.repository_owner}}/oppia.wiki.git
      - name: Deploy
        run: |
          git push deployment develop:master
